config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:index, :new, :create, :destroy]
  resources :items, only: [:index, :show]
  resources :bakeries, only: [:index, :show]
  resources :customers

  get '/sign_in', to: 'sessions#sign_in'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy'
  root 'application#hello'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bakery.rb
class Bakery < ApplicationRecord
    has_many :recipes
    has_many :items, through: :recipes
    has_many :orders
    has_many :customers, through: :orders

    def most_popular
        self.items.sort{ |item|
            item.orders.count
        }.reverse[0]
    end
    
    def most_valued_customer
        self.customers.max_by{|c| 
        (c.orders.select{|o|
         o.bakery_id == self.id}).count
        }
    end

    def most_valued_customer_name
        self.most_valued_customer.full_name
    end

    def most_valued_customer_orders
        self.most_valued_customer.orders.select{|order| order.bakery_id == self.id}
    end

    def total_sales
        (self.orders.collect{|order| order.item}).sum{|item| item.price}
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    has_many :items, through: :orders 
    has_many :bakeries, through: :orders
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    has_secure_password

    def full_name
        self.first_name + " " + self.last_name
    end

    def favorite_item
        fave = (self.orders.group_by{| order | order.item}).max_by{ |k,v| v.count }
        fave[0]
    end
    def favorite_bakery
        bakeries_group = self.orders.group_by{|order| order.bakery}
        fave_bakery = bakeries_group.max{|k,v| v.count}
        fave_bakery
    end
    def favorite_bakery_name
        self.favorite_bakery[0].name
    end
    def favorite_bakery_id
        self.favorite_bakery[0].id
    end
    def favorite_bakery_times_ordered
        self.favorite_bakery[1].count
    end

    def orders_by_date
        self.orders.sort_by{ |orders|
            orders.created_at
        }.reverse
    end
    def orders_by_bakery
        self.orders.sort_by{ |orders|
            orders.bakery_id
        }.reverse
    end

    def order_history_by_bakery
         ((self.orders_by_bakery.group_by{|order| order.bakery_id }).map{|k,v| k = Bakery.find(k), v = v}).to_h
    end

    def order_history_by_date
        self.orders_by_date.group_by{|o| o.created_at.strftime("%D")}
    end
    #total spent on items
    def total_spent
        self.orders.sum{|order| order.item.price}
    end

    # def total_spent_at_bakery(bakery_name)
        #total spent on items by bakery
        # bakery = self.order_history_by_bakery
        #look at all the orders from a specific bakery
        #find the total price of all the items inside the value
    # end

end

app/models/item.rb
class Item < ApplicationRecord
    has_many :recipes
    has_many :bakeries, through: :recipes
    has_many :orders
    has_many :customers, through: :orders
    
    def made_by
        self.recipes.collect{|recipe| recipe.bakery.name }
    end

    def times_purchased
        self.orders.count
    end

    def popular_item?
        if self.times_purchased > 5
            "Hot and Fresh Best Seller!"
        else
            "A tasty treat"
        end
    end
 
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    belongs_to :bakery

    def order_total
        self.item.price 
    end
    
    def  employee_discount
        #apply discount when placing order 
        self.order_total * 0.75
        #dicount price by 25%
    end


end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :item
    belongs_to :bakery
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def hello
        @disable_nav = true
    end
end

app/controllers/bakeries_controller.rb
class BakeriesController < ApplicationController

    def index
        @bakeries = Bakery.all
    end

    def show
        @bakery = Bakery.find(params[:id])
    end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :current_customer, only: [:show, :edit, :update, :destroy]

    def current_customer
        @customer = Customer.find(params[:id])
    end

    def index
        @customers = Customer.all
    end
    
    def show
        @orders = @customer.order_history_by_bakery
        @items = Item.all
    end

    def new
        @customer = Customer.new
    end

    def create
        @customer = Customer.new(custy_params)
        if @customer.valid?
            @customer.save
            redirect_to '/sign_in'
        else
            flash[:errors] = @customer.errors.full_messages
            redirect_to new_customer_path
        end
    end

    def edit 
    end

    def update
        @customer.update(custy_params)
        if @customer.valid?
            redirect_to customer_path(@customer)
        else
            flash[:errors] = @customer.errors.full_messages
            redirect_to edit_customer_path(@customer)
        end
    end

    def destroy
        @customer.destroy
        redirect_to '/'
    end

    private

    def custy_params
        params.require(:customer).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.all
    end

    def show
        @item = Item.find(params[:id])
    end

    #We want to create a new item. That will be done via recipes#new.
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
    
    def index
        @orders = Order.all
    end

    def new
        # byebug
        @order = Order.new
        @customers = Customer.all
        @customer = Customer.find(session[:id])
        @bakeries = Bakery.all
        @bakery = Bakery.find(params[:bakery])
        @items = @bakery.items
    end

    def create
        # byebug
        items_list = (params[:order][:item_id][1..:item_id.length])
        items_list.each do |item_id|
            @order = Order.new
            @order.customer_id = session[:id]
            @order.item_id = item_id
            @order.bakery_id = params[:order][:bakery_id]
            @order.save
        end
        redirect_to customer_path(session[:id])
    end

    def destroy

    end

    private

    def order_params
        params.require(:order).permit( :customer_id, :bakery_id, :item_id => [])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def sign_in
        @disable_nav = true
        @customer = Customer.new
    end

    def create
        # check customer password input vs customer password in db 
        # .authenticate
        # find customerr
        # check if there is a customer&& if their password matches
        # THEN store id in session
        # byebug
        @customer = Customer.find_by(email: params[:customer][:email])
        # byebug
        if @customer && @customer.authenticate(params[:customer][:password])
            session[:id] = @customer.id
            session[:name] = @customer.full_name
            redirect_to bakeries_path
        else
            flash[:error] = "Incorrect Email or Password"
            redirect_to '/sign_in'
        end

    end

    def destroy
        session.clear
        redirect_to '/sign_in'
    end

    private 

    def customer_params
        params.require(:customer).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bakeries_helper.rb
module BakeriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/application/hello.html.erb
<div class="header"><h1> Welcome to Hot and Fresh! </h1><hr></div>

<h2><%= link_to "Sign In Here", sign_in_path%></h2>

<h2><%=link_to "Don't have an account? Create one!", new_customer_path   %></h2>

app/views/bakeries/index.html.erb
<h1>All the Bakeries</h1><hr>

<div class="list_info">
    <% @bakeries.each do |bakery| %>
        <li id="bakery_list">
            <%= link_to bakery.name, bakery_path(bakery) %>
        </li>
    <% end %>
</div>
<hr>
<footer> Logged in As: <%= link_to session[:name], customer_path(session[:id])%> 
<%= button_to "Logout", {controller: 'sessions', action: 'destroy'}, method: 'delete' %>
</footer>

app/views/bakeries/show.html.erb
<h1><%= @bakery.name %></h1>
<br>
<h3 class="info">
    Located in <%= @bakery.location%><br>
    <%= @bakery.created_at.strftime("Open since %Y")%>
        <br><br>
    Most popular item: <%=link_to @bakery.most_popular.name.capitalize, item_path(@bakery.most_popular.id)%><br> 
    Most valued customer: <%= link_to @bakery.most_valued_customer_name, customer_path(@bakery.most_valued_customer.id)%> 
    with <%= @bakery.most_valued_customer_orders.count%> orders!
</h3>
<br>
<h2 class="list_title">Tasty Offerings</h2>
<div class="list_info">
    <p>
        <% @bakery.items.each do |item| %>
            <li id="bakery_item">
                <%= link_to item.name.capitalize, item_path(item) %> - $<%= item.price%>.00
            </li>
        <% end %>
    </p>
</div>
<div class="link"><%= button_to "Place an Order", {controller: 'orders', action: 'new'}, params: {bakery: @bakery, customer: session[:id]}, method: "get"%></div>
<br>
<div class="link"><%= link_to "Return to All Bakeries", bakeries_path %></div>

<br>
<footer> Logged in As: <%= link_to session[:name], customer_path(session[:id])%> 
<%= button_to "Logout", {controller: 'sessions', action: 'destroy'}, method: 'delete' %>
</footer>

app/views/customers/_form.html.erb
<%= form_with model: @customer do |f| %>
<%=f.label :first_name%>
<%=f.text_field :first_name%><br><br>

<%=f.label :last_name%>
<%=f.text_field :last_name%><br><br>

<%=f.label :email%>
<%=f.text_field :email%><br><br>

<%=f.label :password%>
<%=f.password_field :password%><br><br>

<%=f.submit%>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit Account Info</h1>

<% if flash[:errors]%>
    <% flash[:errors].each do |error|%>
        <li style="color:red">
            <%= error %>
        </li>
    <% end %>
<% end %>

<%= render 'form'%>

app/views/customers/index.html.erb
<h1>All the Customers</h1>

<h2>
    <% @customers.each do |customer| %>
        <li>
            <%= link_to customer.full_name, customer_path(customer) %>
        </li>
    <% end %>
</h2>

app/views/customers/new.html.erb
<h1>Create an Account</h1>

<% if flash[:errors]%>
    <% flash[:errors].each do |error|%>
        <li style="color:red">
            <%= error %>
        </li>
    <% end %>
<% end %>

<%= render 'form' %>

app/views/customers/show.html.erb
<h1><%= @customer.full_name %></h1><hr>

<h3 class="info">
    <%= @customer.created_at.strftime("Customer since %B %d, %Y") %><br><br>
    Favorite treat: <%= link_to @customer.favorite_item.name.capitalize, item_path(@customer.favorite_item.id)%><br>
    Favorite Bakery: <%= link_to @customer.favorite_bakery_name, bakery_path(@customer.favorite_bakery_id)%> with
    <%= @customer.favorite_bakery_times_ordered%> orders.<br>
    Total spent on pastries: $<%= @customer.total_spent%>.00
</h3>


<h2 class="list_title">Order History:</h2>
<div class="list_info">
    <p><% @orders.each do |key, value| %>
        <li>
            <u id="bakery_name"><%= link_to key.name, bakery_path(key) %> </u><br>
            <% value.each do |value_data| %>
                <li>
                    <%=link_to (@items.find(value_data.item_id).name.capitalize), 
                    item_path(@items.find(value_data.item_id))%> - ordered on
                    <%=value_data.created_at.strftime("%D at %r")%>
                </li>
            <% end %>
        </li>
    <% end %>
    </p>
</div>
<br>
<div id="delete_link">
    <%= link_to('Delete Account', customer_path(@customer), method: "delete") %>
</div>
<br>
<br>
<div class="return_link">
    <%= link_to "Return to Main Page", "/"%>
</div>
<br>
<br>
<footer> Logged in As: <%= link_to session[:name], customer_path(session[:id])%><br>
<%=button_to "Logout", {controller: 'sessions', action: 'destroy'}, method: 'delete'%>
</footer>

app/views/items/index.html.erb
<h1>All the Tasty Treats</h1>

<p class="list_info">
    <% @items.each do |item|%>
        <li>
            <%= link_to item.name, item_path(item) %>
        </li>
    <% end %>
</p>

app/views/items/show.html.erb
<h1><%= @item.name.capitalize %></h1><hr>

<h3 class="info"><%= @item.popular_item? %></h3>

<h2 class="list_title"> Bakeries that sell <%= @item.name.capitalize %></h2>
<div class="list_info">
    <% @item.bakeries.each do |bakery| %>
        <li id="bakery_list">
            <%= link_to bakery.name, bakery_path(bakery) %>
        </li>
    <% end %>
</div>
<br>

<%=link_to "Return to Previous Page", :back %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hot & Fresh</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href=<%=customer_path(session[:id])%>>Profile<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/bakeries">Bakeries</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/items">Items</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hot & Fresh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' unless @disable_nav %>
    <%= yield %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Make an Order with <%= @bakery.name%> </h1>

<%= form_with model: @order do |f| %>

<%=f.hidden_field :bakery_id, value: @bakery.id %>

<%=f.collection_select :customer_id, @customers, :id, :full_name, {include_blank: @customer.full_name} %><br><br>

<%=f.label :tasty_treats%><br>
<%=f.collection_check_boxes :item_id, @items, :id, :name%><br><br>

<%=f.submit "Place Order"%>
<% end %><br>

<hr>
<footer> Logged in As: <%= link_to session[:name], customer_path(session[:id])%> 
<%= button_to "Logout", {controller: 'sessions', action: 'destroy'}, method: 'delete' %>
</footer>